apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresop1-deployment
  namespace: dbanking-namespace
  labels:
    app: postgres-op1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-op1
  template:
    metadata:
      labels:
        app: postgres-op1
    spec:
      containers:
      - name: postgres
        image: dbankingop1cntrregistry.azurecr.io/dbanking-op1-postgres:latest
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: dBanking_CMS
        ports:
        - containerPort: 5432