apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresop2-deployment
  namespace: dbanking-namespace
  labels:
    app: postgres-op2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-op2
  template:
    metadata:
      labels:
        app: postgres-op2
    spec:
      containers:
      - name: postgres
        image: dbankingop1cntrregistry.azurecr.io/dbanking-op2-postgres:latest
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: dBanking_profileMgt
        ports:
        - containerPort: 5434